# Generated by Django 3.1.2 on 2020-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20201119_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
