# Generated by Django 3.1.2 on 2020-11-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_blog_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
