# Generated by Django 3.1.2 on 2020-11-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_blog_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='like',
        ),
    ]
