# Generated by Django 3.1.2 on 2020-12-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_auto_20201218_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
    ]
